version: '3.8'

services:
  # Базы данных
  users-db:
    image: postgres:15
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  orders-db:
    image: postgres:15
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    # volumes:
    #   - orders-data:/var/lib/postgresql/data

  products-db:
    image: postgres:15
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5434:5432"
    # volumes:
    #   - products-data:/var/lib/postgresql/data

  issues-db:
    image: postgres:15
    environment:
      POSTGRES_DB: issues
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5435:5432"
    # volumes:
    #   - issues-data:/var/lib/postgresql/data

  elasticsearch:
    image: postgres:15 #docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      POSTGRES_DB: elasticsearch
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "9200:9200"

  # Микросервисы
  user-auth:
    image: user-auth
    build: ./user-auth
    environment:
      USERS_DB_HOST: users-db
      DB_PORT: 5432
    ports:
      - "8080:8080"

  user-client:
    image: user-client
    build: ./user-client
    environment:
      USERS_DB_HOST: users-db
      DB_PORT: 5433
      USERSERVICE_DB_HOST: users-db
    ports:
      - "3000:3000"
    depends_on:
      - users-db
      - user-service

  user-service:
    image: user-service
    build: ./user-service
    environment:
      ORDERS_DB_HOST: orders-db
      DB_PORT: 5433
    ports:
      - "8081:8080"
    depends_on:
      - orders-db
      - elasticsearch

  order-service:
    image: order-service
    build: ./order-service
    environment:
      ORDERS_DB_HOST: orders-db
      DB_PORT: 5432
    ports:
      - "8082:8080"
    depends_on:
      - orders-db
      - elasticsearch

  watchdog:
    image: watchdog
    build: ./watchdog
    environment:
      ORDERS_DB_HOST: orders-db
      PRODUCTS_DB_HOST: products-db
      ISSUES_DB_HOST: issues-db
      DB_PORT: 5432
    ports:
      - "8083:8080"
    depends_on:
      - orders-db
      - products-db
      - issues-db
      - issuemanaging-service

  issuemanaging-service:
    image: issuemanaging-service
    build: ./issuemanaging-service
    environment:
      ISSUES_DB_HOST: issues-db
      DB_PORT: 5432
    ports:
      - "8084:8080"
    depends_on:
      - issues-db

  issuemanaging-cli:
    image: issuemanaging-cli
    build: ./issuemanaging-cli
    depends_on:
      - issuemanaging-service

  issuemanaging-auth:
    image: issuemanaging-auth
    build: ./issuemanaging-auth
    environment:
      USERS_DB_HOST: users-db
      DB_HOST: 5432
    ports:
      - "8085:8080"
    depends_on:
      - users-db

volumes:
  users-data:
  orders-data:
  products-data:
  issues-data:
